CREATE TABLE IF NOT EXISTS value_data (
    value_id varchar PRIMARY KEY,
    block_hash varchar,
    received_time TIMESTAMP,
    received_value varchar,
    coin_name varchar
);

CREATE TABLE IF NOT EXISTS addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_name varchar,
    coin_name varchar
);